var num1 = 5;
var num2 = 6;
var num3 = 7;
var num4 = 8;
var string1 = "hey";
var string2 = "wassup";
var string3 = "hello";
var bool1 = true;
var bool2 = false;
var x;

console.log("the first string", string1);
console.log("the second string", string2);
console.log("the third string", string3);
console.log("the first number", num1);
console.log("the second number", num2);
console.log("the third number", num3);
console.log("the fourth number", num4);
console.log("the first boolean", bool1);
console.log("the second boolean", bool2);
console.log("the undefined variable", x);
